-- CREATE DATABASE COLLEGE_DB;
-- USE COLLEGE_DB;

-- CREATE TABLE STUDENT(
-- USN VARCHAR(10) PRIMARY KEY,
-- SName VARCHAR(30),
-- Address VARCHAR(50),
-- Phone VARCHAR(10),
-- Gender VARCHAR(10)
-- );

-- CREATE TABLE SEMSEC(
-- SSID VARCHAR(5) PRIMARY KEY,
-- Sem INT,
-- Sec CHAR(1)
-- );

-- CREATE TABLE CLASS(
-- USN VARCHAR(10),
-- SSID VARCHAR(5),
-- PRIMARY KEY(USN, SSID),
-- FOREIGN KEY (USN) REFERENCES STUDENT(USN),
-- FOREIGN KEY (SSID) REFERENCES SEMSEC(SSID)
-- );

-- CREATE TABLE COURSE(
-- Subcode VARCHAR(10) PRIMARY KEY,
-- Title VARCHAR(30),
-- Sem INT,
-- Credits INT
-- );

-- CREATE TABLE IAMARKS(
-- USN VARCHAR(10),
-- Subcode VARCHAR(10),
-- SSID VARCHAR(5),
-- Test1 INT,
-- Test2 INT,
-- Test3 INT,
-- FinalIA INT,
-- PRIMARY KEY(USN, Subcode, SSID),
-- FOREIGN KEY (USN) REFERENCES STUDENT(USN),
-- FOREIGN KEY (Subcode) REFERENCES COURSE(Subcode),
-- FOREIGN KEY (SSID) REFERENCES SEMSEC(SSID)
-- );

-- INSERT INTO STUDENT VALUES
-- ('4MH22CS200','Rahul','Bangalore','9876543210','Male'),
-- ('4MH22CS201','Anita','Mysore','9876543211','Female'),
-- ('4MH22CS202','Ravi','Tumkur','9876543212','Male'),
-- ('4MH22CS203','Pooja','Bangalore','9876543213','Female');

-- SELECT * FROM STUDENT;

-- INSERT INTO SEMSEC VALUES
-- ('S1',4,'C'),
-- ('S2',4,'A'),
-- ('S3',5,'B');

-- SELECT * FROM SEMSEC;

-- INSERT INTO CLASS VALUES
-- ('4MH22CS200','S1'),
-- ('4MH22CS201','S1'),
-- ('4MH22CS202','S2'),
-- ('4MH22CS203','S1');

-- SELECT * FROM CLASS;

-- INSERT INTO COURSE VALUES
-- ('CS401','DBMS',4,4),
-- ('CS402','Operating System',4,4),
-- ('CS403','Computer Networks',4,3);

-- SELECT * FROM COURSE;

-- INSERT INTO IAMARKS VALUES
-- ('4MH22CS200','CS401','S1',18,19,20,NULL),
-- ('4MH22CS200','CS402','S1',15,17,16,NULL),
-- ('4MH22CS201','CS401','S1',10,12,14,NULL),
-- ('4MH22CS203','CS403','S1',8,10,9,NULL);

-- SELECT * FROM IAMARKS;

-- SELECT S.*
-- FROM STUDENT S
-- JOIN CLASS C ON S.USN = C.USN
-- JOIN SEMSEC SS ON C.SSID = SS.SSID
-- WHERE SS.Sem = 4 AND SS.Sec = 'C';

-- SELECT SS.Sem, SS.Sec, S.Gender, COUNT(*) AS Total
-- FROM STUDENT S
-- JOIN CLASS C ON S.USN = C.USN
-- JOIN SEMSEC SS ON C.SSID = SS.SSID
-- GROUP BY SS.Sem, SS.Sec, S.Gender;

-- CREATE VIEW TEST1_MARKS AS
-- SELECT Subcode, Test1
-- FROM IAMARKS
-- WHERE USN = '4MH22CS200';

-- SELECT * FROM TEST1_MARKS;

-- UPDATE IAMARKS
-- SET FinalIA =
-- (GREATEST(Test1,Test2) +
-- GREATEST(Test2,Test3) +
-- GREATEST(Test1,Test3) -
-- LEAST(Test1,Test2,Test3)) / 2;
-- LEAST(Test1,Test2,Test3)) / 2;
-- LEAST(Test1,Test2,Test3)) / 2;

-- SELECT * FROM IAMARKS;

-- SELECT S.USN, S.SName, SS.Sem, SS.Sec, I.FinalIA,
-- CASE
-- WHEN FinalIA BETWEEN 17 AND 20 THEN 'Outstanding'
-- WHEN FinalIA BETWEEN 12 AND 16 THEN 'Average'
-- WHEN FinalIA < 12 THEN 'Weak'
-- END AS Category
-- FROM STUDENT S
-- JOIN CLASS C ON S.USN=C.USN
-- JOIN SEMSEC SS ON C.SSID=SS.SSID
-- JOIN IAMARKS I ON S.USN=I.USN
-- WHERE SS.Sem=4;